export const CHANGE_TAB = 'CHANGE_TAB'
export const DO_SEARCH_SUGGEST = 'DO_SEARCH_SUGGEST'
export const SEARCH = 'SEARCH'
export const GET_SEARCH_SUGGEST = 'GET_SEARCH_SUGGEST'
export const DO_SEARCH_CLEAR = 'DO_SEARCH_CLEAR'
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST'

